# Generated by Django 5.0.7 on 2024-07-20 17:26

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images")),
                ("content", models.TextField()),
                (
                    "blog_slug",
                    autoslug.fields.AutoSlugField(
                        default=None, editable=False, populate_from="title", unique=True
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Popular", "Popular"),
                            ("Recent", "Recent"),
                            ("Trending", "Trending"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Main_post", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="HOME.category",
                    ),
                ),
            ],
        ),
    ]
