# Generated by Django 5.0.7 on 2024-07-21 01:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOME", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("1", "PUBLISH"), ("0", "DRAFT")], default=0, max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="section",
            field=models.CharField(
                choices=[
                    ("Recent", "Recent"),
                    ("Publish", "Publish"),
                    ("Trending", "Trending"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
