# Generated by Django 5.0.7 on 2024-07-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOME", "0002_blog_status_alter_blog_blog_slug_alter_blog_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="section",
            field=models.CharField(
                choices=[
                    ("Trending", "Trending"),
                    ("Recent", "Recent"),
                    ("Popular", "Popular"),
                ],
                max_length=100,
            ),
        ),
    ]
