# Generated by Django 5.0.7 on 2024-08-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOME", "0004_alter_blog_section_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="section",
            field=models.CharField(
                choices=[
                    ("Recent", "Recent"),
                    ("Trending", "Trending"),
                    ("Popular", "Popular"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("0", "DRAFT"), ("1", "PUBLISH")], default=0, max_length=1
            ),
        ),
    ]
