# Generated by Django 5.1 on 2024-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOME", "0005_blog_views_alter_blog_section_alter_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="section",
            field=models.CharField(
                choices=[
                    ("Recent", "Recent"),
                    ("Popular", "Popular"),
                    ("Trending", "Trending"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("1", "PUBLISH"), ("0", "DRAFT")], default=0, max_length=1
            ),
        ),
    ]
